TARGET_ARCH := x86_64
TARGET_CPU_ABI := x86_64
TARGET_ARCH_VARIANT := silvermont

TARGET_2ND_CPU_ABI := x86
TARGET_2ND_ARCH := x86
TARGET_2ND_ARCH_VARIANT := silvermont

TARGET_USES_64_BIT_BINDER := true
